### PR TITLE
Frameless window w/ features (Winapi)

### PR DESCRIPTION
**Pull request by NovusTheory**
Going from issue #81 I was very interested in learning this more as the current frameless implementation is very limited and rendered useless at the moment as you can't resize or even drag the window. I have since added this implementation successfully.

*Note: All border margins may not be ideal and can be adjusted, especially for CefGlue.Winapi*

### Current Implementation
- **CefSharp.Winapi** has full proper frameless window with resize, aero snap, and ability to drag the window by setting elements with `-webkit-app-region: drag`. This has the full frameless window experience Electron has.
- **CefGlue.Winapi (Partial)** currently has a frameless window with the ability to resize, aero snap, and drag the window but **canot** be modified with `-webkit-app-region: drag` as .NETStandard has some missing System.Drawing classes. Border margins currently not adjustable to suit the needs of individual apps. Should I add an API for this? It might be a quick to obselete method until a solution can be figured out for `-webkit-app-region`.

I do not expect this PR to be merged right away as it is not a full flawless implementation yet.

### CODE REVIEW

**Comment by mattkol** [comment]
@NovusTheory we  will look closely after a branch merge we are working on.
Draggable functionality will be great! 
Thanks.

 @FrankPfattheicher @Fiahblade

**Comment by NovusTheory** [comment]
Thanks! I'll fix the conflicts when necessary after a better review.

**Comment by mattkol** [comment]
@NovusTheory a quick question:

src/Chromely.CefSharp.Winapi/BrowserWindow/HostBase.cs:
````csharp
 - MultiThreadedMessageLoop = true,
 + MultiThreadedMessageLoop = false, // MultiThreadedMessageLoop is not allowed to be used as it will break frameless mode
````
You mean this will be false for all options? Or just for frameless?

**Comment by NovusTheory** [comment]
@mattkol That is actually currently set to false for all options. I can re-enable it for non-frameless mode.

**Comment by mattkol** [comment]
@NovusTheory ok. Thanks.

**Pull request merged**
