### PR TITLE
Support for external configuration

### PR DESCRIPTION
**Pull request by RupertAvery**
Extract ChromelyConfiguration into an interface and associated changes to consumers to allow extension

### CODE REVIEW

**Comment by RupertAvery** [comment]
Related to Issue #91

**Comment by FrankPfattheicher** [comment]
@RupertAvery  Can  you please provide an example showing a benefit of this?

**Comment by mattkol** [comment]
@FrankPfattheicher I believe this is related to discussions in https://github.com/chromelyapps/Chromely/issues/91.

**Comment by mattkol** [comment]
@RupertAvery @FrankPfattheicher I believe this is concluded.
Closing. Please reopen if need be.

**Pull request closed without merging**
