### PR TITLE
Added Production ready HttpSchemaHandler that omits X-Frame-Options header from http responces

### PR DESCRIPTION
**Pull request by Soarc**
See #86 to more of discussion on original issue

### CODE REVIEW

**Comment by mattkol** [comment]
@Soarc thanks for sharing the production ready code.

Couple of things though ..

1. We need to make it customizable. Since we are mostly adding or removing headers. We can add options to do that - add headers, remove headers - the class to extend will be - [ChromelySchemeHandler](https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.Core/ChromelySchemeHandler.cs) and other options that are needed.

2. We need to rename the Scheme handler properly. The current scheme handling we have are for local resources/requests. This change will let Chromely enhance support for embedding as pointed out by @NovusTheory. So I am thinking something like RemoteUrlHttpSchemeHandler, or ProxyHttpSchemeHandler, or ExternalUrlHttpSchemeHandler .. anything that differentiates it from local handlers.

Please let us know what you think.

@Fiahblade @FrankPfattheicher

**Comment by Soarc** [comment]
@mattkol I can rework (what about "ExternalRequestSchemeHandler"? ), so it will encapsulate working with CefRequest and expose working with HttpRequest via virtual methods. 

I'll add API description a  bit later

**Comment by mattkol** [comment]
@Soarc perfect! Thanks.

**Comment by Soarc** [comment]
Renamed NoXFrameOptionsHttpSchemaHandler into ExternalRequestSchemaHandler.
Refactor ExternalRequestSchemaHandler and move async loading code into CefGlueAsyncHandlerBase class, so it could be reused.
Moved HttpHeaders loading into separate method, that can be overrided.
Moved AllowUnsafeBlocks out of conditional blocks, so it will be always enabled.

**Comment by mattkol** [comment]
@Soarc thank you!
We will test over the next few days.

**Comment by mattkol** [comment]
@Soarc just getting to testing and adding this to the configuration. I see that this is only done for CefGlue. I assume it will just be a simple replication for CefSharp. Or did you notice anything that may not work for CefSharp?

Thanks.

**Pull request merged**
